### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by WhosNickDoglio** [anthonycr/Mockingbird#1]
When can I use this???

**Comment by anthonycr** [comment]
I accidentally let my publishing domain expire last year so I am in the process of renewing so I can publish to maven central under the `com.anthonycr` namespace.

**Comment by anthonycr** [comment]
Got my domain set up and working on publishing this week

**Comment by anthonycr** [comment]
Initial version 0.0.1 released. Closed by #10
