### ISSUE TITLE
KSP codgen breaks when using fake<T> or fake(T::class.java)

### ISSUE THREAD

**Issue by WhosNickDoglio** [anthonycr/Mockingbird#57]
```kotlin

class MyViewModelTest {
    @Verify 
    private val logger: Logger = fake()
    // DOn't work
//    private val logger = fake<Logger>()
//    private val logger = fake(Logger::class.java)

    @Test fun `verify fetchData is logged`() {
        val viewModel = MyViewModel(logger)
        viewModel.fetchData()
        verify(logger) {
            logger.info("fetchData was called")
        }
    }
}
```

Running the test with `private val logger: Logger = fake()` the first time will fail but the KSP code will generate as expected. If I try to refactor to either of the other syntax's for defining the fake logger the KSP code will not generate. 

```
e: [ksp] Only interfaces can be verified
e: Error occurred in KSP, check log for detail
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':libraries:makers:kspTestKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
   
  ```

**Comment by anthonycr** [comment]
The core problem is that when KSP runs, the `fake` function doesn't exist, so the return type and subsequent property type is an error type. I might be able to solve this by exposing a stub `fun <T> fake(): T` but not 100% sure yet how to set it up. `compileOnly` works, so maybe the `core` dependency gets moved to a `compileOnly` and then I code gen everything in it 🤔
