### ISSUE TITLE
KSP2/K2 support

### ISSUE THREAD

**Issue by WhosNickDoglio** [anthonycr/Mockingbird#8]
https://android-developers.googleblog.com/2023/12/ksp2-preview-kotlin-k2-standalone.html

I haven't looked too hard into this so this is just mostly for tracking and ensuring mockingbird is compatible with the changes coming in both KSP2 and the K2 compiler.

**Comment by anthonycr** [comment]
Closed by https://github.com/anthonycr/Mockingbird/pull/48
